jobs:
  - ${{ each platform in parameters.platforms }}:
    - ${{ each nodeVersion in parameters.nodeVersions }}:
      - job:
        displayName: ${{ format('{0} node v{1}', platform, nodeVersion) }}
        timeoutInMinutes: 120

        pool:
          vmImage: $(imageName)
        steps:
        - task: UsePythonVersion@0
          displayName: Setup Python
          inputs:
            versionSpec: '2.7'
            architecture: 'x64'
        - task: NodeTool@0
          displayName: Install Node
          inputs:
            versionSpec: $(nodeVersion)
        # - script: sudo apt-get update && sudo apt-get install -y gcc-4.9 g++-4.9
        #   condition: contains(variables['Agent.JobName'], 'linux')
        #   displayName: Install Linux build dependencies
        - script: choco install visualcpp-build-tools --version 14.0.25420.1 -fy && npm config set msvs_version 2015
          condition: contains(variables['Agent.JobName'], 'windows_2015')
          displayName: Install Windows build dependencies
        - script: choco install nasm -fy
          displayName: Install Windows Assembler (NASM)
          condition: contains(variables['Agent.JobName'], 'windows')
        - script: npm ci
          displayName: Install dependencies
        - script: node js2bin.js --ci --node=$(nodeVersion)  --size=2MB --size=4MB --upload --clean
          displayName: Build base node binaries
          env:
            GITHUB_TOKEN: $(PersonalGithubToken)
